title: "John Apessos"
name: "John Apessos"
description: "Mechanical Engineering student at Cornell University"

baseurl: "/fall-2025-portfolio-ja823-maker"
theme: minima

markdown: kramdown

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: "none"

header_pages:
  - cv.md
  - cuad.md
  - 3270_analysis.md
  - 3260_suspension_analysis.md
  - 4300_ba_analysis.md

