title: "John Apessos"
name: "John Apessos"
description: "Mechanical Engineering student at Cornell University"

baseurl: "/fall-2025-portfolio-ja823-maker"
theme: minima

markdown: kramdown

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: "none"

nav:
  - name: "John Apessos"
    link: /
  - name: "CV"
    link: /cv.html
  - name: "CUAD"
    link: /cuad.html
  - name: "3270 Analysis"
    link: /3270_analysis.html
  - name: "3260 Suspension Analysis"
    link: /3260_suspension_analysis.html
  - name: "4300 BA Analysis"
    link: /4300_ba_analysis.html
